# Generated by Django 6.0.5 on 2026-05-11 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='logos')),
                ('gre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='NucleosGroup',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='Schools.school',
                    ),
                ),
            ],
        ),
    ]
