# Generated by Django 6.0.5 on 2026-05-15 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
