# Generated by Django 6.0.5 on 2026-05-15 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_alter_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleosgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='nucleosgroup',
            table='nucleos_group',
        ),
    ]
