# Generated by Django 6.0.5 on 2026-05-11 23:27

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classroom', '0001_initial'),
        ('Schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                (
                    'nucleos_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='Schools.nucleosgroup',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'coordinator',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('date_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
                (
                    'vetor_facial',
                    pgvector.django.vector.VectorField(dimensions=128),
                ),
                (
                    'sala',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='Classroom.classroom',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
