# Generated by Django 6.0.5 on 2026-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sala',
            new_name='classroom',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vetor_facial',
        ),
        migrations.AddField(
            model_name='student',
            name='vector_facial',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
