# Generated by Django 6.0.5 on 2026-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rename_user_id_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rule',
            field=models.CharField(
                choices=[
                    ('PENDING', 'pending'),
                    ('STUDENT', 'student'),
                    ('COORDINATOR', 'coordinator'),
                    ('DIRECTOR', 'director'),
                    ('ADMIN', 'admin'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
