# Generated by Django 6.0.5 on 2026-05-11 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('course', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                (
                    'nucleos_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='Schools.nucleosgroup',
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='Schools.school',
                    ),
                ),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
    ]
