# Generated by Django 6.0.5 on 2026-05-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
