# Generated by Django 6.0.5 on 2026-05-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_alter_classroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
